### PR TITLE
fixed n+1 query issue on tags page

### LINKED ISSUE #365: Tags page has n+1 queries.
**Describe the bug**
After reading #364 I realized Tags Page can be loaded in lesser queries.

**To Reproduce**
1. Go to '[tags page](http://https://circuitverse.org/projects/tags)'
2. Check puma logs

**Expected behavior**
Can be done in lesser queries

**Screenshots**
image

**Desktop (please complete the following information):**
Platform Independent

**Additional context**
The same solution as suggested in #364 can work

**Are you working on this issue? (Yes/No)**
Yes

### PR DESCRIPTION
**Pull request by shubhankarsharma00**
Fixes #365  
#### Describe the changes you have made in this pr -
Now the tags page always load in 3 queries instead of n+1 queries it was using earlier
### Screenshots of the changes (If any) -
image

### CODE REVIEW

File: app/controllers/projects_controller.rb [hunk 1]
```diff
@@ -13,7 +13,7 @@ def index
   end
   # GET /projects/tags/[tag]
   def get_projects
-    @projects = Project.tagged_with(params[:tag]).open
+    @projects = Project.tagged_with(params[:tag]).open.includes(:tags).includes(:author)
```
Comment (tachyons) [inline app/controllers/projects_controller.rb]:
```suggestion
    @projects = Project.tagged_with(params[:tag]).open.includes(:tags, :author)
```
