### PR TITLE
Fixes extra bit lines in splitter on adding space

### LINKED ISSUE #336: Extra bit lines in splitter on adding space on bitWidth split prompt
**Describe the bug**
Adding Extra space on splitter bitWidth Split prompt creates extra lines.

**To Reproduce**
click on splitter, then type 4 as bitwidth, then type "1&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;&nbsp;1 1" as bitwidth split.

**Expected behavior**
The no of bit lines should be 4.

**Screenshots**
The no of bit lines are 9 instead of 4.
Screenshot (2)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome, Firefox

**Are you working on this issue? (Yes/No)**
Yes

### PR DESCRIPTION
**Pull request by NavonilDas**
Fixes #336 

#### Describe the changes you have made in this pr -
Adding more Space on bitWidth Split prompt will not create extra split lines.

### Screenshots -
splitter

### CODE REVIEW

**Comment by Amansingla97** [comment]
Hey can you just try to resolve this conflict. seems like a quick fix.

File: public/js/modules.js [hunk 1]
```diff
@@ -1507,7 +1507,7 @@ function Splitter(x, y, scope = globalScope, dir = "RIGHT", bitWidth = undefined
     CircuitElement.call(this, x, y, scope, dir, bitWidth);
     this.rectangleObject = false;
 
-    this.bitWidthSplit = bitWidthSplit || prompt("Enter bitWidth Split").split(' ').map(function(x) {
+    this.bitWidthSplit = bitWidthSplit || prompt("Enter bitWidth Split").split(' ').filter(x => x != '').map(function(x) {
```
Comment (satu0king) [inline public/js/modules.js]: Looks good but can you can try and use`.trim().split(' ')` instead maybe?

**Comment by satu0king** [comment]
Please resolve the conflicts.

File: public/js/modules.js (hunk 1 above)
Comment (satu0king) [reply public/js/modules.js]: Oh, my bad, I think the thing you are trying to do, won't be fixed by this, it can better be fixed by regex but this is good enough.
