### PR TITLE
fix: lms assignment grade scale fix to 1-100

### LINKED ISSUE #2361: Grade scaling fix to 1-100 for LTI Assignments
First checkout to the `lms-lti` branch and run CircuitVerse locally

1. Login to your account
2. Go to the Group page by clicking on `My-Groups`
3. Click on any existing group (if you haven't any create one)
4. Click on the `+Add Assignment`
After Clicking you will see the screen shown below
image

### Expected Feature
If the checkbox shown above is clicked then the grading scale should be automatically be fixed at `1-100` scale and the field should be disabled. Add corresponding checks in the controller if necessary.
image

### Reference Code
https://github.com/CircuitVerse/CircuitVerse/blob/261533d00b386dc7721636561c5f91d42384543a/app/views/assignments/_form.html.erb#L15

### Note
1. Please make PR against `lms-lti` branch
2. Please comment below if you are starting work on this issue

### PR DESCRIPTION
**Pull request by ayan-biswas0412**
Fixes #2361

#### Describe the changes you have made in this PR -
* Grading scale will be 1-100 for all LTI integrated assignments
* Proper validators has been added to the `assignment model` to check if the correct grading scale is chosen
* In the frontend side when the checkbox will be ticked the grading scale will be changed to 1-100 and will go to readonly mode

### Screenshots of the changes (If any) -
Frontend changes and makes the field readonly on ticking the LMS Checkbox
image

When wrong grading scale is passed back to backend
image

### CODE REVIEW

**Comment by ayan-biswas0412** [comment]
@Commit-Lint review

File: app/models/assignment.rb [hunk 1]
```diff
@@ -2,6 +2,7 @@
 
 class Assignment < ApplicationRecord
   validates :name, length: { minimum: 1 }
+  validates :grading_scale, inclusion: { in: %w(percent), message: "needs to be fixed at 1-100 for passing the grade back to LMS" }, if: :lti_integrated?
```
Comment (tachyons) [inline app/models/assignment.rb:5]: Make the error message translatable

**Review by tachyons — APPROVED** [review]

File: app/models/assignment.rb (hunk 1 above)
Comment (ayan-biswas0412) [reply app/models/assignment.rb:5]: I have kept them intentionally hardcoded because our branch will surely get a conflict with `master` for the i18n so finally before merging to master we can resolve all of them at a time

**Review by Shivansh2407 — APPROVED** [review]
Great work @ayan-biswas0412 :tada:
