### PR TITLE
Fix : Blank Space when the User Has all private circuits #2001

### LINKED ISSUE #2001: Dashboard : Blank Space when the User Has all private circuits
**Describe the bug**
When the user has no circuits, there is an indication shown by image that the user does not have any circuits. But if the user creates a new Circuit and Keeps the Project Acces type to be private, Then in that case ( if the user has all the circuits as private ) there is no image shown and the space remains blank.

**To Reproduce**
1. See this Profile https://circuitverse.org/users/59394 . It has only one circuit that too with Private access. If we add more private access projects then the blank space remains.

**Expected behavior**
The same Image with No Circuits Indication Can be displayed.

**Screenshots**
No Circuits : 

image

All Circuits with Private Access : 
 
From Main User Dashboard :
image

From Other User's End : 

image

**Device Information [optional]:**
 - OS: [Windows]
 - Browser [Chrome]

**Are you working on this issue? (Yes/No)**
No

### PR DESCRIPTION
**Pull request by pulkit-30**
Fixes #2001 

#### Describe the changes you have made in this PR -
The same Image with No Circuits Indication is displayed when the User has all Private Circuits.

 ### Screenshots of the changes (If any) -
#### From the Main User Dashboard
Screenshot 2021-12-15 at 8 30 10 PM

#### From theGuest User Dashboard
Screenshot 2021-12-15 at 9 00 34 PM

Inspired from #2025 

Please provide me with appropriate feedback so I can continue working on this.

### CODE REVIEW

File: app/controllers/users/circuitverse_controller.rb [hunk 1]
```diff
@@ -11,6 +11,10 @@ class Users::CircuitverseController < ApplicationController
   def index
     @profile = ProfileDecorator.new(@user)
     @projects = @user.rated_projects
+    public_projects = @user.projects.map do |project|
+      policy(project).check_direct_view_access?
+    end
+    @public_projects_exist = public_projects.include?(true)
```
Comment (tachyons) [inline app/controllers/users/circuitverse_controller.rb:17]: If you want to check if public projects exists, most perfomant way is to use

```suggestion
   public_projects_exist = @user.projects.open.exists?
```

Comment (pulkit-30) [reply app/controllers/users/circuitverse_controller.rb:17]: Yes Sir this is correct,
But with this change, the admin user will not able to see his own private projects(if he has only private projects) instead it will show the `No result image`.

https://user-images.githubusercontent.com/76155456/146793412-fdbca57f-5a17-4cc9-b76a-687f91210c8f.mov

See, when the User has 1 private and 1 public project, there is no problem,
But deleting the public one, then it will not show the private project to the User.

Please check.

Comment (tachyons) [reply app/controllers/users/circuitverse_controller.rb:17]: That means you were setting wrong value to public_projects_exist, right ?

Comment (pulkit-30) [reply app/controllers/users/circuitverse_controller.rb:17]: No, I think this is correct.

Comment (pulkit-30) [reply app/controllers/users/circuitverse_controller.rb]: Hey @tachyons,
I have updated this PR,
I was wrong, about the above statement ( > No sir, I think this is correct.)
I am sorry for that 😔, learning from my mistakes
Please review 
Thanks

**Comment by tachyons** [comment]
Thanks
