### PR TITLE
fix:fixed multiple ocurrence of india

### LINKED ISSUE #2792: Multiple options for India in countries.
**Describe the bug**
In case geocoder returns India there are multiple occurrences of India in select options for countries.

**To Reproduce**
1. Go to 'Edit profile page'
2. Click on the country select element

**Expected behavior**
There should be only one option for India.

**Screenshots**
Screenshot from 2022-01-17 05-50-15

**Device Information [optional]:**
 - OS: Ubuntu
 - Browser: Chrome

**Are you working on this issue? Yes**

### PR DESCRIPTION
**Pull request by shukapurv**
Fixes #2792

#### Describe the changes you have made in this PR -
Used conditionals to skip prepend when geocoder returns india.

### Screenshots of the changes (If any) -
**Before:**
Screenshot from 2022-01-17 05-50-15

**After:**
Screenshot from 2022-01-17 06-07-04

### CODE REVIEW

**Review by Kartikay304 — APPROVED** [review]

File: app/helpers/users_circuitverse_helper.rb [hunk 1]
```diff
@@ -4,7 +4,9 @@ module UsersCircuitverseHelper
   def get_priority_countries
     priority_countries = ["IN"]
     geo_contry = Geocoder.search(request.remote_ip).first&.country
-    priority_countries.prepend(geo_contry) unless geo_contry.nil?
+    if geo_contry != "IN"
```
Comment (tachyons) [inline app/helpers/users_circuitverse_helper.rb:7]:
```suggestion
    if priority_countries.include?(geo_country)
```
make it more generic
