### PR TITLE
Empty project

### LINKED ISSUE #262: Unable to save an empty project
Saving an empty project produces an error.

Create a new project, click 'save online', enter a project name, and see the error.

(Not working on this issue)

### PR DESCRIPTION
**Pull request by Amansingla97**
Fixes #262
Screenshot 2019-03-18 at 9 18 58 AM
Quick fix. I hope this solves the issue.let me know if something more is requires :)

### CODE REVIEW

File: app/controllers/simulator_controller.rb [hunk 1]
```diff
@@ -60,12 +60,23 @@ def create
     @project.author = current_user
 
     data_url = params[:image]
-    jpeg      = Base64.decode64(data_url['data:image/jpeg;base64,'.length .. -1])
-    image_file = File.new("preview_#{Time.now()}.jpeg", "wb")
-    image_file.write(jpeg)
+
+    str =data_url['data:image/jpeg;base64,'.length .. -1];
```
[the remark this answers is not in the document]
Comment (Amansingla97) [reply app/controllers/simulator_controller.rb]: Done

**Comment by ankitkataria** [comment]
@Amansingla97 I think we'll need a similar check in the `update` method as well. You can create a helper in `app/helpers/utils.rb` and use it in both `create` and `update`.

**Comment by Amansingla97** [comment]
@ankitkataria  I think u mean to say app/helpers/simulator_helper.rb.

**Comment by ankitkataria** [comment]
It's up to you to include it wherever you want to, my point is making a helper function out of it. :smile:

File: app/helpers/simulator_helper.rb [hunk 2]
```diff
@@ -1,2 +1,25 @@
...
+      image_file = File.new("preview_#{Time.now()}.jpeg", "wb")
+      image_file.write(jpeg)
+    end
+
+    image_file
+  end
+
+  def check_to_delete (data_url)
+    str = data_url["data:image/jpeg;base64,".length .. -1]
+    if str.to_s.empty?
```
Comment (ankitkataria) [inline app/helpers/simulator_helper.rb]: This is same as `!str.to_s.empty?`

**Comment by Amansingla97** [comment]
Sorry for empty space ,long lone and long method(corrected). Its the first time I am working with codeclimate :P

File: app/controllers/simulator_controller.rb [hunk 3]
```diff
@@ -59,13 +62,14 @@ def create
     @project.name = params[:name]
     @project.author = current_user
 
-    data_url = params[:image]
-    jpeg      = Base64.decode64(data_url['data:image/jpeg;base64,'.length .. -1])
-    image_file = File.new("preview_#{Time.now()}.jpeg", "wb")
-    image_file.write(jpeg)
+    image_file = return_image_file(params[:image])
+
```
Comment (ankitkataria) [inline app/controllers/simulator_controller.rb]: Remove empty line

File: app/controllers/simulator_controller.rb [hunk 4]
```diff
@@ -1,5 +1,5 @@
 class SimulatorController < ApplicationController
-
+  include SimulatorHelper
```
Comment (ankitkataria) [inline app/controllers/simulator_controller.rb]: Is it possible to implement this in a similar fashion as the `Utils` has been used in `collaborations_controller` and `group_members_controller`?

File: app/helpers/simulator_helper.rb [hunk 5]
```diff
@@ -1,2 +1,25 @@
 module SimulatorHelper
+  def return_image_file(data_url)
```
Comment (ankitkataria) [inline app/helpers/simulator_helper.rb]: Look at how `app/helpers/utils.rb` has been implemented. Is it possible to implement it in a similar fashion for the sake of uniformity?

Comment (Amansingla97) [reply app/helpers/simulator_helper.rb]: Obviously it can be placed there but i think keeping it utils sacrifices the readability.

File: app/helpers/simulator_helper.rb (hunk 2 above)
Comment (Amansingla97) [reply app/helpers/simulator_helper.rb]: But we are not declaring str in controller . So we can't use it directly

File: app/controllers/simulator_controller.rb (hunk 4 above)
Comment (Amansingla97) [reply app/controllers/simulator_controller.rb]: Yes it is possible but i prefer to do it this way .

File: app/helpers/simulator_helper.rb (hunk 5 above)
Comment (ankitkataria) [reply app/helpers/simulator_helper.rb]: I agree, I'm asking to implement `SimulatorHelper` is a similar fashion as `Utils` with the helper functions as static methods inside the `SimulatorHelper` and removing the `include` from the `SimulatorController`.

File: app/helpers/simulator_helper.rb (hunk 2 above)
Comment (ankitkataria) [reply app/helpers/simulator_helper.rb]: That's fine, I was suggesting to change the implementation of the helper. :sweat_smile: to a one liner say - `data_url["data:image/jpeg;base64,".length .. -1].to_s.empty?`
Plus `File.delete(image_url) if data_url["data:image/jpeg;base64,".length .. -1].to_s.empty?` seems pretty readable.

File: app/controllers/simulator_controller.rb (hunk 4 above)
Comment (ankitkataria) [reply app/controllers/simulator_controller.rb]: Okay, I felt it would have been better for the overall uniformity in the way helper functions were defined and used :slightly_smiling_face:

**Comment by tachyons** [comment]
Add the tests to cover new behavior

File: app/helpers/simulator_helper.rb (hunk 2 above)
Comment (Amansingla97) [reply app/helpers/simulator_helper.rb]: Bhai data_url bhi define nahi kiya controller mein.

Comment (ankitkataria) [reply app/helpers/simulator_helper.rb]: Does this work? 
```
def check_to_delete (data_url)
    !data_url["data:image/jpeg;base64,".length .. -1.to_s.empty
end
```

Comment (Amansingla97) [reply app/helpers/simulator_helper.rb]: yup this would work :). but i prefer to do it this way .

Comment (ankitkataria) [reply app/helpers/simulator_helper.rb]: Okay :+1: , I was suggesting for a one-line implementation for helper. Pardon me for not being more clear here. :smile:

Comment (tachyons) [reply app/helpers/simulator_helper.rb]: I agree with ankit here. This is a standard ruby idiom

File: app/helpers/simulator_helper.rb (hunk 5 above)
Comment (tachyons) [reply app/helpers/simulator_helper.rb]: Helpers are supposed to be implemented as modules. But one downside is helpers have global scope. Since this logic is specific to simulator controller it is better to keep it in simulator controller itself as private methods

File: app/helpers/simulator_helper.rb (hunk 2 above)
Comment (Amansingla97) [reply app/helpers/simulator_helper.rb]: cool

File: app/helpers/simulator_helper.rb (hunk 5 above)
Comment (Amansingla97) [reply app/helpers/simulator_helper.rb]: cool

**Comment by satu0king** [comment]
Instead of no preview available, can you simply have this image located at - https://circuitverse.org/img/default.png

Actually, this is carrierwave's default image and it should kick in automatically if there is no image associated.

In the case of updating a circuit when there is no image, we can simply not update the image, the previous image is fine. What do you think about this approach? 

image

**Comment by Amansingla97** [comment]
@satu0king 
In the case of updating a circuit 
->When there is no image I don't find any reason to keep the previous image as the user have already decided to delete it.
->Keeping previous image creates unnecessary confusion to user about whether the project is updated (to empty)or not.

**Comment by tachyons** [comment]
Enable rubocop linter in your editor so that you can check the style issues on the fly

**Comment by satu0king** [comment]
> Rather when the project is updated to empty default.png should show up.

It is a matter of preference actually and no it doesn't need to mean the user has deleted the previous circuit, more often than not it could mean that the current circuit which is active is different from the previous circuit. Either approach is acceptable. 

I will test and merge this soon.

File: app/controllers/simulator_controller.rb (hunk 4 above)
Comment (satu0king) [reply app/controllers/simulator_controller.rb]: We will need a major refactor of all these things probably during the GSoC period. We will need to have guidelines on these things so that there is no confusion.

**Comment by satu0king** [comment]
Thanks!
