### PR TITLE
Fix: clashing inputs on generating 2 combinational circuits #2203

### LINKED ISSUE #2203: clashing inputs on generating 2 combinational circuits
**Describe the bug**
Simulator overwrites the first input element when generating 2nd combinational circuit with different boolean variables.

**To Reproduce**
1. Go to '[simulator](https://circuitverse.org/simulator)'
2. Click on 'tools>combinational analysis.'
4. Create a combinational circuit with boolean variables A, B, C ... and generate a circuit.
5. Repeat steps 1 to 4 with unused boolean variables. 
**Expected behavior**
A new circuit should be generated away from the existing circuit.

**Screenshots**
image

**Are you working on this issue? (Yes/No)**
No.

### PR DESCRIPTION
**Pull request by pulkit-30**
Fixes #2203 

Simulator overwrites the first input element when generating 2nd combinational circuit with different boolean variables.

#### Describe the changes you have made in this PR -

Before:

before changes

After 

after changes

Please provide me with appropriate feedback so that I can continue working on this.

### CODE REVIEW

**Comment by pulkit-30** [comment]
Hey @gr455 , please review this PR 
Thanks :D

File: simulator/src/combinationalAnalysis.js [hunk 1]
```diff
@@ -240,6 +243,15 @@ function drawCombinationalAnalysis(combinationalData, inputList, outputListNames
     var startPosY = 200;
 
     var currentPosY = 300;
+    if (simulationArea.maxWidth && simulationArea.maxHeight) {
+        if (simulationArea.maxHeight + 300 > simulationArea.maxWidth) {
```
Comment (gr455) [inline simulator/src/combinationalAnalysis.js:247]: Hey @pulkit-30 Can you explain why the height and width relation like this is required?

Comment (gr455) [reply simulator/src/combinationalAnalysis.js:247]: Also I would suggest putting the `300` into some variable with an appropriate name to avoid magic numbers

Comment (pulkit-30) [reply simulator/src/combinationalAnalysis.js:247]: > Hey @pulkit-30 Can you explain why the height and width relation like this is required?

Yep! 
small logic to prevent growth in a single dimension

ref: https://github.com/CircuitVerse/CircuitVerse/pull/2205#issuecomment-823231798

Comment (gr455) [reply simulator/src/combinationalAnalysis.js:247]: Oh understood. Can you just make the `300` into a variable. Then we're good to go

Comment (pulkit-30) [reply simulator/src/combinationalAnalysis.js]: Done 🚀

**Comment by gr455** [comment]
Thanks a lot :rocket:
