### PR TITLE
Fix XSS in project and circuit names

### LINKED ISSUE #375: Serious XSS issue in subcircuit/newCircuit name
serious XSS security vulnerability exists in subcircuit name
If successfully exploited attacker can steal your cookie and make malicious request from victims browser
**To Reproduce**
1.launch simulator 
2. Click on new Circuit +
3. Give this subcirccuit a name as {subcktname} <script>alert(1);</script>
for example a payload would be sbckt<script>alert(1);</script>
4. Ctrl+S
See the error
5.Now logout 
6.launch the created project in preview mode as any other user or as guest/non-authenticated user 
7. Again see the alert(1) script is executed
**Expected behavior**
all the user input must be validated and escaped for the dangerous cross-sitite scripting attack vectors

#note this attack not only affects the user who created the project but also all other who open the project. 
**Screenshots**
ckt2
ckt5

**Desktop (please complete the following information):**
 - OS:any
 - Browser[ tested on chrome,should be replicable to other browser like Firefox ]

**Additional context**
My exploited  project .url https://circuitverse.org/users/5423/projects/15040
open the url and a alert script will only show in your browser I did bnot made it malicious but it can be made .
https://github.com/CircuitVerse/CircuitVerse/issues/248

Are you working on this issue :Yes

### PR DESCRIPTION
**Pull request by ankitkataria**
Fixes #375 #248 

#### Describe the changes you have made in this pr -

If the name of the project/sub circuit contains tags then they are stripped. 

### Screenshots of the changes (If any) -
`project name contains xss`
image

`script tags have been stripped`
image

PS. Increased method-length to 100 in code climate config to prevent errors in java script code as methods are usually long. Ruby code's method length is enforced through rubocop

### CODE REVIEW

File: app/helpers/utils.rb [hunk 1]
```diff
@@ -27,4 +27,10 @@ def self.mail_notice(input_mails, parsed_mails, newly_added)
                "No valid Email(s) entered."
              end
   end
+
+  # To strip tags from input data
+  # @param input data string
+  def self.stripTags(input)
+    input.present? ? input.gsub(/(<([^>]+)>)/iu, "").strip() : nil
+  end
```
Comment (satu0king) [inline app/helpers/utils.rb]: Is there a built-in rails function to do this?

Comment (ankitkataria) [reply app/helpers/utils.rb]: Yes, as tachyons also pointed out, using sanitize helper now.
