### PR TITLE
Fix search paginator gap

### LINKED ISSUE #334: Search failing on large search
Goto: https://circuitverse.org/search?utf8=%E2%9C%93&q=test

Error: ` ActionView::Template::Error (uninitialized constant SearchPaginateRenderer::ELLIPSIS)`

**Are you working on this issue? (Yes/No)**
No

### PR DESCRIPTION
**Pull request by ankitkataria**
Fixes #334 

#### Describe the changes you have made in this pr -

Fix `gap` in `search_paginate_renderer.rb`

### Screenshots of the changes (If any) -
image

### CODE REVIEW

**Comment by Amansingla97** [comment]
looks good can merge it 👍

**Comment by ankitkataria** [comment]
@satu0king Is there something left to be done in this pr? The search seems to down on the website for some time.

File: config/initializers/search_paginate_renderer.rb [hunk 1]
```diff
@@ -29,7 +29,8 @@ def previous_or_next_page(page, text, classname)
   end
 
   def gap
-    tag :li, tag(:i, ELLIPSIS, class: 'page-link'), class: 'page-item disabled'
+    text = @template.will_paginate_translate(:page_gap) { '&hellip;' }
+    %(<li class="page-item disabled" style="padding: 0 8px"> #{text} </li>)
```
Comment (satu0king) [inline config/initializers/search_paginate_renderer.rb]: Can you explain what is happening here?
